# Generated by Django 5.2.4 on 2025-07-14 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('menu_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('menu_url', models.CharField(max_length=250, unique=True)),
                ('menu_icon', models.CharField(blank=True, max_length=250, null=True)),
                ('parent_id', models.IntegerField()),
                ('is_main_menu', models.BooleanField(default=False)),
                ('is_sub_menu', models.BooleanField(default=False)),
                ('is_sub_child_menu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_list',
            },
        ),
    ]
